; Reference https://gist.github.com/LeopoldTal/2aa79947c4cab728402c4054d6733254
(define draw-point (lambda (x y)
    (display "*")))

(let* (
    (step 0.045)
    (step-x (/ step 2))
    (step-y step)
    (lines 53)
    (columns 151)
    (center-x -0.6)
    (center-y 0)
    )
    (let loop1 ((cur-line 0)) (if (< cur-line lines)
        (let ((y (+ center-y (* step-y (- (* 0.5 lines) cur-line 0.5)))))
            (let loop2 ((cur-col 0)) (if (< cur-col columns)
                (let ((x (- center-x (* step-x (- (* 0.5 columns) cur-col 0.5)))))
                   (draw-point x y)
                   (loop2 (+ cur-col 1))
                )))
            (newline)
            (loop1 (+ cur-line 1)))
        )))
